'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Check, ClipboardCheck, Loader2, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { documentService } from '@/services/document.service';
import { ReviewTask } from '@/types/api.types';
export default function ReviewsPage() { const [status, setStatus] = useState('pending'); const [tasks, setTasks] = useState<ReviewTask[]>([]); const [loading, setLoading] = useState(true); const [comment, setComment] = useState<Record<string,string>>({}); const [error, setError] = useState(''); const load = async () => { setLoading(true); try { setTasks((await documentService.tasks(status)).items); } catch (e) { setError(e instanceof Error ? e.message : '无法加载审核任务'); } finally { setLoading(false); } }; useEffect(() => { void Promise.resolve().then(load); // data callback owns state updates
  // eslint-disable-next-line react-hooks/exhaustive-deps
}, [status]); const decide = async (task: ReviewTask, approve: boolean) => { const text = comment[task.id]?.trim() || ''; if (!approve && !text) { setError('驳回时请填写审核意见'); return; } try { if (approve) await documentService.approve(task.id, text); else await documentService.reject(task.id, text); await load(); } catch (e) { setError(e instanceof Error ? e.message : '审核操作失败'); } }; return <div className="h-full overflow-auto"><header className="border-b px-6 py-5"><h1 className="text-2xl font-semibold">审核工作台</h1><p className="mt-1 text-sm text-muted-foreground">处理提交的知识文档审核任务</p></header><main className="max-w-4xl p-6"><div className="mb-5 flex gap-2">{[['pending','待审核'],['approved','已通过'],['rejected','已驳回']].map(([key,label]) => <Button key={key} variant={status === key ? 'default' : 'outline'} onClick={() => setStatus(key)}>{label}</Button>)}</div>{error && <p className="mb-4 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{loading ? <div className="flex justify-center p-12"><Loader2 className="animate-spin" /></div> : tasks.length === 0 ? <div className="rounded-xl border py-16 text-center text-muted-foreground"><ClipboardCheck className="mx-auto mb-3 size-9" />暂无任务</div> : <div className="space-y-4">{tasks.map((task) => <section key={task.id} className="rounded-xl border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><Link href={`/documents/${task.documentId}`} className="font-semibold hover:text-primary">文档 #{task.documentId}</Link><p className="mt-1 text-sm text-muted-foreground">提交于 {new Date(task.createdAt).toLocaleString('zh-CN')} · 提审前为{task.beforeStatus === 1 ? '已发布' : '草稿'}</p></div>{task.reviewResult && <span className="text-sm">{task.reviewResult === 1 ? '已通过' : '已驳回'}</span>}</div>{status === 'pending' ? <><Textarea className="mt-4" value={comment[task.id] || ''} onChange={(e) => setComment({ ...comment, [task.id]: e.target.value })} placeholder="填写审核意见（驳回时必填）" /><div className="mt-3 flex justify-end gap-2"><Button variant="outline" onClick={() => void decide(task, false)}><X />驳回</Button><Button onClick={() => void decide(task, true)}><Check />通过</Button></div></> : task.reviewComment && <p className="mt-3 rounded-lg bg-muted p-3 text-sm">{task.reviewComment}</p>}</section>)}</div>}</main></div>; }
